const express=require("express");const path=require("path");const os=require("os");const fs=require("fs");const fsp=require("fs/promises");const multer=require("multer");const ffmpeg=require("fluent-ffmpeg");const FormData=require("form-data");const axios=require("axios");
ffmpeg.setFfmpegPath("/usr/bin/ffmpeg");ffmpeg.setFfprobePath("/usr/bin/ffprobe");
const app=express();const PORT=process.env.PORT||3000;const upload=multer({dest:os.tmpdir(),limits:{fileSize:500*1024*1024}});
app.use(express.static(path.join(__dirname,"public")));
function cleanup(paths){for(const p of paths){if(!p)continue;try{if(fs.existsSync(p))fs.unlinkSync(p)}catch{}}}
function parseNumber(value,fallback=0){const n=Number(value);return Number.isFinite(n)?n:fallback}
function uniqueTemp(name){return path.join(os.tmpdir(),`${Date.now()}-${Math.random().toString(36).slice(2)}-${name}`)}
async function streamToFile(response,filePath){const arrayBuffer=await response.arrayBuffer();await fsp.writeFile(filePath,Buffer.from(arrayBuffer))}
function probeDuration(filePath){return new Promise((resolve,reject)=>{ffmpeg.ffprobe(filePath,(err,data)=>{if(err)return reject(err);resolve(Number(data?.format?.duration||0))})})}
function runFfmpeg({inputPath,outputPath,trimStart=0,clipDuration=0,videoFilter,audioFilter,crf=23}){return new Promise((resolve,reject)=>{let stderrLines=[];let cmd=ffmpeg(inputPath).videoCodec("libx264").audioCodec("aac").outputOptions(["-movflags +faststart","-pix_fmt yuv420p","-preset ultrafast",`-crf ${crf}`]).format("mp4").on("stderr",line=>{stderrLines.push(line);if(stderrLines.length>40)stderrLines.shift()}).on("end",resolve).on("error",err=>{err.ffmpegStderr=stderrLines.join(" | ");reject(err)});if(videoFilter)cmd=cmd.videoFilters(videoFilter);if(audioFilter)cmd=cmd.audioFilters(audioFilter);if(trimStart>0)cmd=cmd.setStartTime(trimStart);if(clipDuration>0)cmd=cmd.duration(clipDuration);cmd.save(outputPath)})}
function pickVideoFilter({preset,resolution}){const h=Number(resolution)||1080;const scale=`scale=-2:${h}:flags=bicubic`;if(preset==="clarity")return`${scale},eq=contrast=1.05:brightness=0.01:saturation=1.04,unsharp=3:3:0.4:3:3:0.0`;if(preset==="social")return`${scale},eq=contrast=1.07:brightness=0.02:saturation=1.06`;if(preset==="cinematic")return`${scale},hqdn3d=0.6:0.6:2:2,eq=contrast=1.03:brightness=0.01:saturation=1.02`;return`${scale},eq=contrast=1.03:brightness=0.01:saturation=1.02`}
function pickAudioFilter({audioPreset,audioGain}){const gain=Number(audioGain)||0;const base=[`volume=${gain}dB`];if(audioPreset==="voice")base.push("highpass=f=100","lowpass=f=8000","acompressor=threshold=-18dB:ratio=3:attack=20:release=200");else if(audioPreset==="loud")base.push("loudnorm=I=-14:LRA=11:TP=-1.5");else base.push("loudnorm=I=-16:LRA=11:TP=-1.5");return base.join(",")}
function runMux(videoPath,audioPath,outputPath){return new Promise((resolve,reject)=>{let stderrLines=[];ffmpeg().input(videoPath).input(audioPath).outputOptions(["-map 0:v:0","-map 1:a:0","-c:v copy","-c:a aac","-shortest","-movflags +faststart"]).on("stderr",line=>{stderrLines.push(line);if(stderrLines.length>40)stderrLines.shift()}).on("end",resolve).on("error",err=>{err.ffmpegStderr=stderrLines.join(" | ");reject(err)}).save(outputPath)})}
async function buildTrimInfo(req,inputPath){const trimStart=Math.max(0,parseNumber(req.body.trimStart,0));const trimEnd=Math.max(0,parseNumber(req.body.trimEnd,0));const totalDuration=await probeDuration(inputPath);if(!totalDuration||totalDuration<=0)throw new Error("Could not read video duration.");const endAt=Math.max(trimStart,totalDuration-trimEnd);const clipDuration=Math.max(0,endAt-trimStart);if(clipDuration<=0.1){const err=new Error("Trim values leave no usable video.");err.statusCode=400;throw err}return{trimStart,clipDuration}}
function decodeAxiosErrorData(data){if(!data)return"Unknown error";if(Buffer.isBuffer(data))return data.toString("utf8");if(typeof data==="string")return data;try{return JSON.stringify(data)}catch{return String(data)}}
async function runElevenLabsIsolation(inputPath,originalName,elevenKey){const form=new FormData();form.append("file",fs.createReadStream(inputPath),{filename:originalName||"input.mp4",contentType:"video/mp4"});try{const response=await axios.post("https://api.elevenlabs.io/v1/audio-isolation",form,{headers:{"xi-api-key":elevenKey,...form.getHeaders()},maxBodyLength:Infinity,maxContentLength:Infinity,responseType:"arraybuffer",validateStatus:()=>true});if(response.status<200||response.status>=300){throw new Error(`ElevenLabs failed (${response.status}): ${decodeAxiosErrorData(response.data)}`)}const outPath=uniqueTemp("isolated.mp3");await fsp.writeFile(outPath,Buffer.from(response.data));return outPath}catch(err){if(err.response)throw new Error(`ElevenLabs failed (${err.response.status}): ${decodeAxiosErrorData(err.response.data)}`);throw err}}
async function runFalUpscale(inputPath,falKey,modelId,scaleFactor){const {fal}=await import("@fal-ai/client");const {File}=require("node:buffer");fal.config({credentials:falKey});const data=await fsp.readFile(inputPath);const file=new File([data],"input.mp4",{type:"video/mp4"});const uploadedUrl=await fal.storage.upload(file);const submit=await fal.queue.submit(modelId,{input:{video_url:uploadedUrl,scale_factor:Number(scaleFactor)||2}});const requestId=submit.request_id||submit.requestId;if(!requestId)throw new Error("fal queue submit did not return a request ID.");const startedAt=Date.now(),maxWaitMs=1000*60*30;while(true){const status=await fal.queue.status(modelId,{requestId,logs:true});const st=status.status||status.state||"";if(st==="COMPLETED"){const result=await fal.queue.result(modelId,{requestId});const videoUrl=result?.data?.video?.url||result?.video?.url||result?.data?.url||result?.url;if(!videoUrl)throw new Error("fal completed, but no output video URL was returned.");const outPath=uniqueTemp("fal-video.mp4");const res=await fetch(videoUrl);if(!res.ok)throw new Error(`Could not download fal output (${res.status}).`);await streamToFile(res,outPath);return outPath}if(st==="FAILED"||st==="CANCELLED")throw new Error(`fal job ended with status ${st}.`);if(Date.now()-startedAt>maxWaitMs)throw new Error("fal job timed out while waiting for completion.");await new Promise(r=>setTimeout(r,5000))}}
app.post("/api/enhance-fast",upload.single("media"),async(req,res)=>{let inputPath=req.file?.path||null,outputPath=null;try{if(!req.file)return res.status(400).json({error:"No media file uploaded."});const {trimStart,clipDuration}=await buildTrimInfo(req,inputPath);outputPath=uniqueTemp("fast-output.mp4");await runFfmpeg({inputPath,outputPath,trimStart,clipDuration,videoFilter:pickVideoFilter({preset:req.body.preset,resolution:req.body.resolution}),audioFilter:pickAudioFilter({audioPreset:req.body.audioPreset,audioGain:req.body.audioGain}),crf:Math.min(32,Math.max(18,parseNumber(req.body.crf,23)))});const stat=fs.statSync(outputPath);if(!stat.size)throw new Error("Processed file is empty.");res.setHeader("Content-Type","video/mp4");res.setHeader("Content-Disposition",`attachment; filename="fast-enhanced.mp4"`);const stream=fs.createReadStream(outputPath);stream.pipe(res);stream.on("close",()=>cleanup([inputPath,outputPath]));stream.on("error",()=>cleanup([inputPath,outputPath]))}catch(error){cleanup([inputPath,outputPath]);res.status(error.statusCode||500).json({error:error.message||"Fast enhancement failed.",stderr:error.ffmpegStderr||""})}});
app.post("/api/enhance-ai",upload.single("media"),async(req,res)=>{let inputPath=req.file?.path||null,aiVideoPath=null,isolatedAudioPath=null,outputPath=null;try{if(!req.file)return res.status(400).json({error:"No media file uploaded."});const elevenKey=(req.body.elevenKey||"").trim();const falKey=(req.body.falKey||"").trim();const modelId=(req.body.falModelId||"clarityai/crystal-video-upscaler").trim();const scaleFactor=req.body.scaleFactor||"2";if(!elevenKey||!falKey)return res.status(400).json({error:"Both ElevenLabs and fal API keys are required for AI Enhance."});const {trimStart,clipDuration}=await buildTrimInfo(req,inputPath);const trimmedInputPath=uniqueTemp("trimmed-input.mp4");await runFfmpeg({inputPath,outputPath:trimmedInputPath,trimStart,clipDuration,videoFilter:null,audioFilter:null,crf:20});cleanup([inputPath]);inputPath=trimmedInputPath;isolatedAudioPath=await runElevenLabsIsolation(inputPath,req.file.originalname,elevenKey);aiVideoPath=await runFalUpscale(inputPath,falKey,modelId,scaleFactor);outputPath=uniqueTemp("ai-output.mp4");await runMux(aiVideoPath,isolatedAudioPath,outputPath);const stat=fs.statSync(outputPath);if(!stat.size)throw new Error("AI output file is empty.");res.setHeader("Content-Type","video/mp4");res.setHeader("Content-Disposition",`attachment; filename="ai-enhanced.mp4"`);const stream=fs.createReadStream(outputPath);stream.pipe(res);stream.on("close",()=>cleanup([inputPath,aiVideoPath,isolatedAudioPath,outputPath]));stream.on("error",()=>cleanup([inputPath,aiVideoPath,isolatedAudioPath,outputPath]))}catch(error){cleanup([inputPath,aiVideoPath,isolatedAudioPath,outputPath]);res.status(error.statusCode||500).json({error:error.message||"AI enhancement failed.",details:"Check that your ElevenLabs key, fal key, and selected fal model are valid and enabled on your account.",stderr:error.ffmpegStderr||""})}});
app.get("/healthz",(_req,res)=>res.json({ok:true}));app.listen(PORT,"0.0.0.0",()=>{console.log(`Media Enhancer Pro listening on port ${PORT}`)});